### ISSUE TITLE
Crash on startup : duplicate ID

### ISSUE THREAD

**Issue by RedsaphirCZ** [stuntmania/PlaceableItems#3]
Crash-log said duplicate ID: don't 1.7.10 get rid of IDs? I am not sure what to do about it.
Log here: http://pastebin.com/wQ1huSjj

**Comment by emx2000** [comment]
When does the crash occur?

**Comment by stuntmania** [comment]
I found the issue, the ID we use for ender eye blocks is the same as the Botania mod. I'll change it in our source code, recompile it and send a new version ASAP on the curseforge. Tell me if it crashes again.

**Comment by RedsaphirCZ** [comment]
Still crashes, still duplikate id
Log: http://pastebin.com/eg5kjQa8

**Comment by stuntmania** [comment]
Alright, here is a private build for testing purpose. Can you tell me if it works now?
http://www.mediafire.com/download/280w0un1locnrhr/placeableitems-test.jar

**Comment by RedsaphirCZ** [comment]
Still same crash

http://pastebin.com/8ykwWU7W

**Comment by RedsaphirCZ** [comment]
Works without botania.
Maybe you should ask Vazkii

**Comment by stuntmania** [comment]
Ok I found the issue, the bug is fixed on my local machine. You can find the version on the curseforge project. Thanks for bringing up the problem :+1:
