### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by XBlackLeopardX** [stuntmania/PlaceableItems#4]
When placing a steak on the ground and eating it, it causes the server to crash
Im using the latest version of everything

https://gist.github.com/XBlackLeopardX/3f825acb46dd2d75b704

**Comment by stuntmania** [comment]
I will try to find how this crash is happening. Does it crash with every single food in the game?

**Comment by XBlackLeopardX** [comment]
tried it with melon slices and yes it crashed the server couldnt seem to place any of the other ones like raw chicken or raw fish or pumpkin pie

**Comment by stuntmania** [comment]
I uploaded a fix on the curse forge, keep me updated.

**Comment by XBlackLeopardX** [comment]
Yupp the fix works!
sorry for the late reply was busy

**Comment by stuntmania** [comment]
It's fine, thanks for bringing this to our attention!
